CREATE USER CASA_DISCOGRAFICA
  IDENTIFIED BY  musica
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;

-- 2 Roles for CASA_DISCOGRAFICA 
GRANT CONNECT TO CASA_DISCOGRAFICA;
GRANT RESOURCE TO CASA_DISCOGRAFICA;
ALTER USER CASA_DISCOGRAFICA DEFAULT ROLE ALL;

-- 1 Tablespace Quota for CASA_DISCOGRAFICA 
ALTER USER CASA_DISCOGRAFICA QUOTA UNLIMITED ON USERS;


--------------------------------------------------------------------------------

