CREATE TABLE AGENZIA_BOOKING
(
  IBAN              CHAR(27 BYTE),
  NOME_AGENZIA      VARCHAR2(15 BYTE),
  EMAIL_AGENZIA     VARCHAR2(30 BYTE),
  TELEFONO_AGENZIA  VARCHAR2(12 BYTE),
  ID_CITTA_AGENZIA  NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE TABLE ALBUM
(
  ID_ALBUM        VARCHAR2(3 BYTE),
  TITOLO          VARCHAR2(40 BYTE)             NOT NULL,
  NUMERO_CANZONI  NUMBER(2)                     NOT NULL,
  DURATA_ALBUM    VARCHAR2(15 BYTE),
  GENERE          VARCHAR2(30 BYTE),
  DATA_USCITA     DATE                          NOT NULL,
  ARTISTA         VARCHAR2(3 BYTE)              NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE TABLE ARTISTA
(
  ID_ARTISTA         VARCHAR2(3 BYTE),
  NOME_ARTE          VARCHAR2(30 BYTE),
  EMAIL_ARTISTA      VARCHAR2(30 BYTE)          NOT NULL,
  NUMERO_COMPONENTI  NUMBER(1),
  TELEFONO_ARTISTA   VARCHAR2(10 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE TABLE AUTORE
(
  CF_AUTORE       CHAR(16 BYTE),
  NOME_AUTORE     VARCHAR2(15 BYTE)             NOT NULL,
  COGNOME_AUTORE  VARCHAR2(15 BYTE)             NOT NULL,
  NOME_ARTE       VARCHAR2(30 BYTE),
  SESSO_AUTORE    CHAR(1 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE TABLE CANZONE
(
  ID_CANZONE      VARCHAR2(3 BYTE)              NOT NULL,
  NOME_CANZONE    VARCHAR2(50 BYTE)             NOT NULL,
  DURATA_CANZONE  VARCHAR2(50 BYTE),
  ARTISTA         VARCHAR2(3 BYTE)              NOT NULL,
  ALBUM           VARCHAR2(3 BYTE)              NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE TABLE CATEGORIA_PREMIO
(
  PREMIO            VARCHAR2(15 BYTE),
  CATEGORIA_PREMIO  VARCHAR2(50 BYTE)           NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE TABLE CITTA
(
  ID_CITTA    NUMBER,
  NOME_CITTA  VARCHAR2(50 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE TABLE CONCERTI
(
  ID_CONCERTO    NUMBER,
  NOME_CONCERTO  VARCHAR2(50 BYTE),
  DATA_CONCERTO  DATE,
  ARTISTA        VARCHAR2(3 BYTE)               NOT NULL,
  CODICE_IBAN    CHAR(27 BYTE)                  NOT NULL,
  ID_STRUTTURA   NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE TABLE CONTRATTO
(
  ID_CONTRATTO       NUMBER,
  INIZIO_CONTRATTO   DATE,
  STIPENDIO_ARTISTA  NUMBER(4),
  DURATA_CONTRATTO   DATE                       NOT NULL,
  ARTISTA            VARCHAR2(3 BYTE)           NOT NULL,
  MANAGER            CHAR(16 BYTE)              NOT NULL,
  STIPENDIO_MANAGER  NUMBER(4)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE TABLE DIRITTI_AUTORE
(
  CODICE          VARCHAR2(5 BYTE),
  INIZIO_DIRITTO  DATE                          NOT NULL,
  DURATA_DIRITTO  DATE                          NOT NULL,
  ALBUM           VARCHAR2(3 BYTE)              NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE TABLE DISTRIBUITO
(
  ALBUM         VARCHAR2(3 BYTE),
  DISTRIBUTORE  VARCHAR2(20 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE TABLE DISTRIBUTORE
(
  NOME_DISTRIBUTORE      VARCHAR2(20 BYTE),
  EMAIL_DISTRIBUTORE     VARCHAR2(30 BYTE),
  TELEFONO_DISTRIBUTORE  VARCHAR2(12 BYTE),
  PARTITA_IVA            CHAR(11 BYTE),
  ID_CITTA_DISTRIBUTORE  NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE TABLE FORMATO
(
  ALBUM    VARCHAR2(3 BYTE),
  FORMATO  VARCHAR2(50 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE TABLE HA
(
  VIDEOCLIP     VARCHAR2(3 BYTE),
  CANZONE       VARCHAR2(3 BYTE),
  USCITA_VIDEO  DATE                            NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE TABLE INDIRIZZI_STUDIO
(
  ID_INDIRIZZO    NUMBER,
  CODICE_POSTALE  VARCHAR2(50 BYTE),
  INDIRIZZO       VARCHAR2(50 BYTE),
  ID_CITTA        NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE TABLE MANAGER
(
  CF_MANAGER       CHAR(16 BYTE),
  NOME_MANAGER     VARCHAR2(15 BYTE)            NOT NULL,
  COGNOME_MANAGER  VARCHAR2(15 BYTE)            NOT NULL,
  DATA_NASCITA     DATE,
  SESSO_MANAGER    CHAR(1 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE TABLE PREMI
(
  NOME_PREMIO  VARCHAR2(50 BYTE),
  GUADAGNO     NUMBER(4)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE TABLE PROMOZIONE
(
  ID_PROMOZIONE      NUMBER,
  ID_CONCERTO        NUMBER                     NOT NULL,
  INIZIO_PROMOZIONE  DATE,
  DURATA             DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE TABLE REGISTRATA
(
  CANZONE             VARCHAR2(3 BYTE),
  STUDIO              VARCHAR2(50 BYTE),
  DATA_REGISTRAZIONE  DATE                      NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE TABLE RICEVE
(
  CANZONE          VARCHAR2(3 BYTE),
  PREMIO           VARCHAR2(15 BYTE),
  CONSEGNA_PREMIO  DATE                         NOT NULL,
  PAESE            VARCHAR2(30 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE TABLE SCRITTA
(
  CANZONE         VARCHAR2(3 BYTE),
  AUTORE          CHAR(16 BYTE),
  DATA_SCRITTURA  DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE TABLE STRUTTURE
(
  ID_STRUTTURA    NUMBER,
  NOME_STRUTTURA  VARCHAR2(50 BYTE),
  ID_CITTA        NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE TABLE STUDIO
(
  NOME_STUDIO   VARCHAR2(50 BYTE),
  TARIFFA       NUMBER(4),
  ID_INDIRIZZO  NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE TABLE TIPO_DISTRIBUTORE
(
  NOME_SOCIETA       VARCHAR2(20 BYTE),
  TIPO_DISTRIBUTORE  VARCHAR2(50 BYTE)          NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE TABLE TIPOLOGIA_PROMOZIONE
(
  ID_TIPO_PROMOZIONE  NUMBER,
  ID_PROMOZIONE       NUMBER,
  TIPO_PROMOZIONE     VARCHAR2(50 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE TABLE TOT_SPESE_LOG
(
  DATA    DATE,
  UTENTE  VARCHAR2(30 BYTE),
  TOTALE  NUMBER,
  ANNO    VARCHAR2(15 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE TABLE VIDEOCLIP
(
  ID_VIDEO      VARCHAR2(3 BYTE),
  NOME_VIDEO    VARCHAR2(50 BYTE)               NOT NULL,
  REGISTA       VARCHAR2(30 BYTE),
  DURATA_VIDEO  VARCHAR2(30 BYTE),
  COSTO         NUMBER(3)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE AGENZIA_BOOKING ADD (
  PRIMARY KEY
  (IBAN)
  ENABLE VALIDATE
,  CONSTRAINT AB1
  UNIQUE (EMAIL_AGENZIA, TELEFONO_AGENZIA)
  ENABLE VALIDATE);

ALTER TABLE ALBUM ADD (
  PRIMARY KEY
  (ID_ALBUM)
  ENABLE VALIDATE);

ALTER TABLE ARTISTA ADD (
  PRIMARY KEY
  (ID_ARTISTA)
  ENABLE VALIDATE
,  CONSTRAINT C1
  UNIQUE (ID_ARTISTA, EMAIL_ARTISTA, NOME_ARTE)
  ENABLE VALIDATE
,  CONSTRAINT C3
  UNIQUE (TELEFONO_ARTISTA)
  ENABLE VALIDATE
,  UNIQUE (EMAIL_ARTISTA)
  ENABLE VALIDATE);

ALTER TABLE AUTORE ADD (
  CONSTRAINT SESSOAUTORE
  CHECK (sesso_autore in ('M','F', 'm', 'f'))
  ENABLE VALIDATE
,  PRIMARY KEY
  (CF_AUTORE)
  ENABLE VALIDATE);

ALTER TABLE CANZONE ADD (
  PRIMARY KEY
  (ID_CANZONE)
  ENABLE VALIDATE);

ALTER TABLE CATEGORIA_PREMIO ADD (
  PRIMARY KEY
  (PREMIO)
  ENABLE VALIDATE);

ALTER TABLE CITTA ADD (
  PRIMARY KEY
  (ID_CITTA)
  ENABLE VALIDATE);

ALTER TABLE CONCERTI ADD (
  PRIMARY KEY
  (ID_CONCERTO)
  ENABLE VALIDATE);

ALTER TABLE CONTRATTO ADD (
  PRIMARY KEY
  (ID_CONTRATTO)
  ENABLE VALIDATE);

ALTER TABLE DIRITTI_AUTORE ADD (
  PRIMARY KEY
  (CODICE)
  ENABLE VALIDATE);

ALTER TABLE DISTRIBUITO ADD (
  CONSTRAINT PKDISTRIBUITO
  PRIMARY KEY
  (ALBUM, DISTRIBUTORE)
  ENABLE VALIDATE);

ALTER TABLE DISTRIBUTORE ADD (
  PRIMARY KEY
  (NOME_DISTRIBUTORE)
  ENABLE VALIDATE
,  UNIQUE (EMAIL_DISTRIBUTORE, TELEFONO_DISTRIBUTORE, PARTITA_IVA)
  ENABLE VALIDATE);

ALTER TABLE FORMATO ADD (
  CONSTRAINT PKFORMATO
  PRIMARY KEY
  (ALBUM, FORMATO)
  ENABLE VALIDATE);

ALTER TABLE HA ADD (
  CONSTRAINT PKHA
  PRIMARY KEY
  (VIDEOCLIP, CANZONE)
  ENABLE VALIDATE);

ALTER TABLE INDIRIZZI_STUDIO ADD (
  PRIMARY KEY
  (ID_INDIRIZZO)
  ENABLE VALIDATE);

ALTER TABLE MANAGER ADD (
  CONSTRAINT SESSO
  CHECK (sesso_manager in ('M','F', 'm', 'f'))
  ENABLE VALIDATE
,  PRIMARY KEY
  (CF_MANAGER)
  ENABLE VALIDATE);

ALTER TABLE PREMI ADD (
  PRIMARY KEY
  (NOME_PREMIO)
  ENABLE VALIDATE);

ALTER TABLE PROMOZIONE ADD (
  PRIMARY KEY
  (ID_PROMOZIONE)
  ENABLE VALIDATE);

ALTER TABLE REGISTRATA ADD (
  CONSTRAINT PKREGISTRATA
  PRIMARY KEY
  (CANZONE, STUDIO)
  ENABLE VALIDATE);

ALTER TABLE RICEVE ADD (
  CONSTRAINT PKRICEVE
  PRIMARY KEY
  (CANZONE, PREMIO, PAESE)
  ENABLE VALIDATE);

ALTER TABLE SCRITTA ADD (
  CONSTRAINT PKSCRITTA
  PRIMARY KEY
  (CANZONE, AUTORE)
  ENABLE VALIDATE);

ALTER TABLE STRUTTURE ADD (
  PRIMARY KEY
  (ID_STRUTTURA)
  ENABLE VALIDATE);

ALTER TABLE STUDIO ADD (
  PRIMARY KEY
  (NOME_STUDIO)
  ENABLE VALIDATE);

ALTER TABLE TIPO_DISTRIBUTORE ADD (
  CONSTRAINT PKDIS
  PRIMARY KEY
  (NOME_SOCIETA, TIPO_DISTRIBUTORE)
  ENABLE VALIDATE);

ALTER TABLE TIPOLOGIA_PROMOZIONE ADD (
  PRIMARY KEY
  (ID_TIPO_PROMOZIONE)
  ENABLE VALIDATE);

ALTER TABLE VIDEOCLIP ADD (
  PRIMARY KEY
  (ID_VIDEO)
  ENABLE VALIDATE
,  CONSTRAINT VIDEONAME
  UNIQUE (NOME_VIDEO)
  ENABLE VALIDATE);
