ALTER TABLE AGENZIA_BOOKING ADD (
  CONSTRAINT FK_CITTA_AGENZIA 
  FOREIGN KEY (ID_CITTA_AGENZIA) 
  REFERENCES CITTA (ID_CITTA)
  ENABLE VALIDATE);

ALTER TABLE ALBUM ADD (
  CONSTRAINT IDARTISTA 
  FOREIGN KEY (ARTISTA) 
  REFERENCES ARTISTA (ID_ARTISTA)
  ENABLE VALIDATE);

ALTER TABLE CANZONE ADD (
  CONSTRAINT FKCANTANTE 
  FOREIGN KEY (ARTISTA) 
  REFERENCES ARTISTA (ID_ARTISTA)
  ENABLE VALIDATE
,  CONSTRAINT FKDISCO 
  FOREIGN KEY (ALBUM) 
  REFERENCES ALBUM (ID_ALBUM)
  ENABLE VALIDATE);

ALTER TABLE CATEGORIA_PREMIO ADD (
  CONSTRAINT PREMI 
  FOREIGN KEY (PREMIO) 
  REFERENCES PREMI (NOME_PREMIO)
  ENABLE VALIDATE);

ALTER TABLE CONCERTI ADD (
  CONSTRAINT FKARTISTA 
  FOREIGN KEY (ARTISTA) 
  REFERENCES ARTISTA (ID_ARTISTA)
  ENABLE VALIDATE
,  CONSTRAINT FK_IBAN 
  FOREIGN KEY (CODICE_IBAN) 
  REFERENCES AGENZIA_BOOKING (IBAN)
  ENABLE VALIDATE
,  CONSTRAINT FK_STRUTTURA 
  FOREIGN KEY (ID_STRUTTURA) 
  REFERENCES STRUTTURE (ID_STRUTTURA)
  ENABLE VALIDATE);

ALTER TABLE CONTRATTO ADD (
  CONSTRAINT CONTRATTO_ART_FK 
  FOREIGN KEY (ARTISTA) 
  REFERENCES ARTISTA (ID_ARTISTA)
  ENABLE VALIDATE
,  CONSTRAINT CONTRATTO_MAN_FK 
  FOREIGN KEY (MANAGER) 
  REFERENCES MANAGER (CF_MANAGER)
  ENABLE VALIDATE);

ALTER TABLE DIRITTI_AUTORE ADD (
  CONSTRAINT DISCO 
  FOREIGN KEY (ALBUM) 
  REFERENCES ALBUM (ID_ALBUM)
  ENABLE VALIDATE);

ALTER TABLE DISTRIBUITO ADD (
  CONSTRAINT FKDIS1 
  FOREIGN KEY (ALBUM) 
  REFERENCES ALBUM (ID_ALBUM)
  ENABLE VALIDATE
,  CONSTRAINT FKDIS2 
  FOREIGN KEY (DISTRIBUTORE) 
  REFERENCES DISTRIBUTORE (NOME_DISTRIBUTORE)
  ENABLE VALIDATE);

ALTER TABLE DISTRIBUTORE ADD (
  CONSTRAINT FK_CITTA_DISTRIBUTORE 
  FOREIGN KEY (ID_CITTA_DISTRIBUTORE) 
  REFERENCES CITTA (ID_CITTA)
  ENABLE VALIDATE);

ALTER TABLE FORMATO ADD (
  CONSTRAINT FKFORMATO 
  FOREIGN KEY (ALBUM) 
  REFERENCES ALBUM (ID_ALBUM)
  ENABLE VALIDATE);

ALTER TABLE HA ADD (
  CONSTRAINT FKCANZONE 
  FOREIGN KEY (CANZONE) 
  REFERENCES CANZONE (ID_CANZONE)
  ENABLE VALIDATE
,  CONSTRAINT FKVIDEO 
  FOREIGN KEY (VIDEOCLIP) 
  REFERENCES VIDEOCLIP (ID_VIDEO)
  ENABLE VALIDATE);

ALTER TABLE INDIRIZZI_STUDIO ADD (
  CONSTRAINT FK_CITTA_INDIRIZZO 
  FOREIGN KEY (ID_CITTA) 
  REFERENCES CITTA (ID_CITTA)
  ENABLE VALIDATE);

ALTER TABLE PROMOZIONE ADD (
  CONSTRAINT PROM_CONCERTO_FK 
  FOREIGN KEY (ID_CONCERTO) 
  REFERENCES CONCERTI (ID_CONCERTO)
  ENABLE VALIDATE);

ALTER TABLE REGISTRATA ADD (
  CONSTRAINT FKREC 
  FOREIGN KEY (CANZONE) 
  REFERENCES CANZONE (ID_CANZONE)
  ENABLE VALIDATE
,  CONSTRAINT FKSTUDIO 
  FOREIGN KEY (STUDIO) 
  REFERENCES STUDIO (NOME_STUDIO)
  ENABLE VALIDATE);

ALTER TABLE RICEVE ADD (
  CONSTRAINT FKPREMIO 
  FOREIGN KEY (PREMIO) 
  REFERENCES PREMI (NOME_PREMIO)
  ENABLE VALIDATE
,  CONSTRAINT FKSINGOLO 
  FOREIGN KEY (CANZONE) 
  REFERENCES CANZONE (ID_CANZONE)
  ENABLE VALIDATE);

ALTER TABLE SCRITTA ADD (
  CONSTRAINT FKCFAUTORE 
  FOREIGN KEY (AUTORE) 
  REFERENCES AUTORE (CF_AUTORE)
  ENABLE VALIDATE
,  CONSTRAINT FKSCRITTA 
  FOREIGN KEY (CANZONE) 
  REFERENCES CANZONE (ID_CANZONE)
  ENABLE VALIDATE);

ALTER TABLE STRUTTURE ADD (
  CONSTRAINT FK_CITTA 
  FOREIGN KEY (ID_CITTA) 
  REFERENCES CITTA (ID_CITTA)
  ENABLE VALIDATE);

ALTER TABLE TIPO_DISTRIBUTORE ADD (
  CONSTRAINT SOCIETA 
  FOREIGN KEY (NOME_SOCIETA) 
  REFERENCES DISTRIBUTORE (NOME_DISTRIBUTORE)
  ENABLE VALIDATE);

ALTER TABLE TIPOLOGIA_PROMOZIONE ADD (
  CONSTRAINT TIPOLOGIA_PROM_FK 
  FOREIGN KEY (ID_PROMOZIONE) 
  REFERENCES PROMOZIONE (ID_PROMOZIONE)
  ENABLE VALIDATE);
