CREATE USER CONTABILE
  IDENTIFIED BY  PASSWORD1
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;

GRANT CONNECT TO CONTABILE;
GRANT RESOURCE TO CONTABILE;
GRANT CREATE SESSION TO CONTABILE;
ALTER USER CONTABILE DEFAULT ROLE ALL;
ALTER USER CONTABILE QUOTA UNLIMITED ON USERS;

GRANT EXECUTE ON CASA_DISCOGRAFICA.AUMENTO_STIPENDIO TO CONTABILE;
GRANT SELECT ON CASA_DISCOGRAFICA.CONTRATTO TO CONTABILE;
GRANT SELECT ON CASA_DISCOGRAFICA.STUDIO TO CONTABILE;
GRANT EXECUTE ON CASA_DISCOGRAFICA.TOT_SPESE TO CONTABILE;
GRANT SELECT ON CASA_DISCOGRAFICA.TOT_SPESE_LOG TO CONTABILE;
GRANT SELECT ON CASA_DISCOGRAFICA.VIDEOCLIP TO CONTABILE;


-------------------------------------------------------------------------------------


CREATE USER IMPIEGATO
  IDENTIFIED BY  PASSWORD2
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
GRANT CONNECT TO  IMPIEGATO;
GRANT RESOURCE TO  IMPIEGATO;
GRANT CREATE SESSION TO  IMPIEGATO;
GRANT CREATE SESSION TO IMPIEGATO;
ALTER USER  IMPIEGATO DEFAULT ROLE ALL;

GRANT SELECT ON CASA_DISCOGRAFICA.AGENZIA_BOOKING TO IMPIEGATO;
GRANT SELECT ON CASA_DISCOGRAFICA.ARTISTA TO IMPIEGATO;
GRANT SELECT ON CASA_DISCOGRAFICA.CONCERTI TO IMPIEGATO;
GRANT SELECT ON CASA_DISCOGRAFICA.CONTRATTO TO IMPIEGATO;
GRANT SELECT ON CASA_DISCOGRAFICA.DISTRIBUITO TO IMPIEGATO;
GRANT SELECT ON CASA_DISCOGRAFICA.DISTRIBUTORE TO IMPIEGATO;
GRANT EXECUTE ON CASA_DISCOGRAFICA.DISTRIBUTORE_ALBUM TO IMPIEGATO;
GRANT EXECUTE ON CASA_DISCOGRAFICA.LIVE TO IMPIEGATO;
GRANT SELECT ON CASA_DISCOGRAFICA.MANAGER TO IMPIEGATO;
GRANT EXECUTE ON CASA_DISCOGRAFICA.NUOVO_CONTRATTO TO IMPIEGATO;
GRANT EXECUTE ON CASA_DISCOGRAFICA.PROMO_CONCERTO TO IMPIEGATO;
GRANT SELECT ON CASA_DISCOGRAFICA.PROMOZIONE TO IMPIEGATO;
GRANT SELECT ON CASA_DISCOGRAFICA.TIPO_DISTRIBUTORE TO IMPIEGATO;
GRANT SELECT ON CASA_DISCOGRAFICA.TIPOLOGIA_PROMOZIONE TO IMPIEGATO;